# .streamlit/secrets.toml
[connections.postgresql]
dialect = "postgresql"
host = "localhost"           # Ou o IP do seu servidor de banco de dados
port = 5432
database = "bd"
username = "seu_usuario"
password = "sua_senha"
